name: test

on:
  # schedule:
  #   - cron:  '0 */6 * * *'
  workflow_dispatch:

jobs:
  prepare:
    name: Prepare job
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.gen-matrix.outputs.matrix }}
      jar: ${{ steps.get-jar.outputs.jar }}
    steps:
      - name: generate matrix
        id: gen-matrix
        run: |
          wget 'https://raw.githubusercontent.com/jmir1/aniyomi-extensions/repo/index.min.json'
          BATCHES=$(jq -cr '{batches:[map(.apk) | _nwise(5)] | to_entries | map({apks:.value, index:.key}) }' index.min.json)
          echo "matrix=$BATCHES" >> $GITHUB_OUTPUT

      - name: get tester jar
        id: get-jar
        run: |
          wget 'https://api.github.com/repos/Claudemirovsky/aniyomi-extensions-tester/releases/latest' -O latest.json
          JAR=$(jq -cr '.assets[0].browser_download_url' latest.json)
          echo "jar=$JAR" >> $GITHUB_OUTPUT

  test_batches:
    name: test batches of extensions
    needs: prepare
    runs-on: ubuntu-latest
    continue-on-error: true
    strategy:
      fail-fast: false
      matrix: ${{ fromJSON(needs.prepare.outputs.matrix) }}
    steps:
      - name: dl tester
        run: |
          JAR=${{ needs.prepare.outputs.jar }}
          wget $JAR -O tester.jar

      - name: dl apks
        id: dl-apks
        run: |
          APKS='${{ toJSON(matrix.batches) }}'
          INDEX=$(jq -cr '.index' <<< $APKS)
          echo "index=$INDEX" >> $GITHUB_OUTPUT
          jq -cr '.apks | .[]' <<< $APKS | while read link; do
            wget https://raw.githubusercontent.com/jmir1/aniyomi-extensions/repo/apk/$link -P apk/
          done

      - name: test apks
        run: |
          # java -jar tester.jar apk -C -D json -P -d
          java -jar tester.jar apk --complete-results --json-dir json --pretty-json --debug

      - name: upload results
        uses: actions/upload-artifact@v3
        with:
          name: "results-${{ steps.dl-apks.outputs.index }}"
          path: "json/"
          retention-days: 1

  generate_results:
    name: generate the results
    needs: test_batches
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          ref: results

      - name: get results
        uses: actions/download-artifact@v3

      - name: check results and make index results file
        id: check
        run: |
          set -x
          COUNT_PASSED=0
          COUNT_ALL=0
          mkdir -p results
          mv results-*/*.json results/
          rm -df results-*
          echo '[' > results.json.tmp
          echo '[' > results.table.json
          while read file; do
            COUNT_ALL=$((COUNT_ALL+1))
            PKGJSON=$(printf '%s\n' "${file#results/results-}")
            PKG=$(printf '%s\n' "${PKGJSON%.json}")
            COUNT=$(jq -cr 'length' $file)
            PASSED_COUNT=$(jq -cr 'map(.results | map(select(.passed != true)) | length == 0) | map(select(. == true)) | length' $file)
            if [[ "$COUNT" == "$PASSED_COUNT" ]]
            then
              COUNT_PASSED=$((COUNT_PASSED+1))
              PASSED=true
              PASSEDEMOJI=✅
            else
              PASSED=false
              PASSEDEMOJI=❌
            fi
            URL=https://raw.githubusercontent.com/jmir1/aet/results/results/results-$PKGJSON
            echo "{\"pkg\":\"$PKG\",\"passed\":$PASSED,\"log\":\"$URL\"}," >> results.json.tmp
            echo "{\"Extension\":\"$PKG\",\"Status\":\"$PASSEDEMOJI\",\"Log\":\"[results-$PKGJSON]($URL)\"}," >> results.table.json
          done < <(find results/*.json)
          sed -i '$ s/.$//' results.json.tmp
          sed -i '$ s/.$//' results.table.json
          echo ']' >> results.json.tmp
          echo ']' >> results.table.json
          jq '.' results.json.tmp > results.json
          rm results.json.tmp
          echo "all=$COUNT_ALL" >> $GITHUB_OUTPUT
          echo "passed=$COUNT_PASSED" >> $GITHUB_OUTPUT

      - name: make table
        run: |
          npm i -g tablemark-cli
          printf "## Extension status\n\n### ${{ steps.check.outputs.passed }}/${{ steps.check.outputs.all }} are working\n\n" > README.md
          tablemark results.table.json -a left -a center -a left >> README.md
          rm results.table.json

      - name: commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Update result files"
          git push
